### ISSUE TITLE
no idea

### ISSUE THREAD

**Issue by newbieinneedofhelp** [voaneves/snake-on-pygame#2]
so whenever i try and run the program i get the following error 
line 9, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

**Comment by voaneves** [comment]
Sorry for taking that long! Didn't realized this issue were here. So, do you have pygame installed?

For windows:
`py -m pip install -U pygame==1.9.6 --user`

For mac:
`python3 -m pip install -U pygame==1.9.6 --user`

For linux:
`sudo apt-get install python-pygame `

If you can, plese try and get back to me.

**Comment by voaneves** [comment]
No answer since them, I'll close it
